### ISSUE TITLE
Stop automatic creation of Recordings directory

### ISSUE THREAD

**Issue by Geoffrian** [ryonakano/reco#20] opened 2019-01-22 22:35 UTC
I do not want another folder created simply by opening the program.

**Comment by ryonakano** [comment] 2019-01-23 11:30
@Geoffrian Thank you for your feedback. I set this folder as a default directory to save recordings, because I was concerned that if I set `~/Music` as a default directory, recordings could be automatically added to the music library every time Music runs.
If we stop automatic creation of Recordings directory, that means we have to set another directory as a default destination, because the app supports both way to save: saving automatically to preset directory, and asking users a destination and save there. Could you tell me where you save your recordings?

**Comment by ryonakano** [comment] 2019-05-18 10:31
It seems other recording apps like Windows Voice Recorder on Windows 10 or GNOME Sound Recorder (which support auto-saving like Reco) also creates a destination folder on the app launch. Although my PR #33 works as intended, I'm going to close this issue because I think the current behavior may not be unnatural as far as referring those corresponding apps.

**Closed by ryonakano** 2019-05-18 10:31 UTC
Labels: Help Wanted, Priority: Low

**Comment by ryonakano** [comment] 2026-04-28 15:24
Just leaving a note that this behavior has gone at some point of release because autosave feature is disabled by default.
