### ISSUE TITLE
Save a previously chosen Microphone choice

### ISSUE THREAD

**Issue by MyMarvel** [ryonakano/reco#283] opened 2024-06-21 08:03 UTC
I have always to select a different microphone when I open the app, it is so annoying. Could you add a feature to remember the mic I choose so when I exit and launch this app next time the same microphone will be preselected, please?

**Comment by nekohayo** [comment] 2024-07-21 16:30
I think this would rather be a duplicate of #234.

**Comment by ryonakano** [comment] 2024-08-14 01:55
Thank you for your request, but I'll close this in favor of #234.

**Closed by ryonakano** 2024-08-14 01:55 UTC
